export const USER_STATE_CHANGE = "USER_STATE_CHANGE";
export const USER_ALL_STATE_CHANGE = "USER_ALL_STATE_CHANGE";
export const USER_POSTS_STATE_CHANGE = "USER_POSTS_STATE_CHANGE";
export const USER_ALL_POSTS_STATE_CHANGE = "USER_ALL_POSTS_STATE_CHANGE";
// export const DICTIONARY_STATE_CHANGE = "DICTIONARY_STATE_CHANGE";
export const FILTERED_DICTIONARY_STATE_CHANGE =
  "FILTERED_DICTIONARY_STATE_CHANGE";
export const VALIDATE_DICTIONARY_STATE_CHANGE =
  "VALIDATE_DICTIONARY_STATE_CHANGE";